Models/Multiplos.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace multiplos_mvc.Models
{
    public class Multiplos
    {   
        public List<string> Numeros { get; set; }
        public static string verificarMultiplos(int num) 
        {
            if(num % 3 == 0 && num % 5 == 0)
            {
                return "FIZZBUZZ";
            } 
            else if(num % 3 == 0) 
            {
                return "FIZZ";
            } 
            else if(num % 5 == 0) 
            {
                return "BUZZ";
            }
            else 
            {
                return Convert.ToString(num);
            }
        }
        public List<string> listarMultiplos()
        {
            Numeros = Enumerable.Range(1, 100).Select(x => verificarMultiplos(x)).ToList();

            return Numeros;
        }
    }
}

Controllers/ActionsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using multiplos_mvc.Models;

namespace multiplos_mvc.Controllers
{
    public class ActionsController : Controller
    {
        public IActionResult Index()
        {
            Multiplos multiplos = new Multiplos();
           
            return View(multiplos.listarMultiplos());
       }
    }
}

Views/Actions/Index.cshtml
@model List<string>

@{
    ViewData["Title"] = "Multiplos";
    int multiploTres = 0, multiploCinco = 0, multiloTresCinco = 0, outroMultiplo = 0;
}

<h1 class="text-center">Lista de Multiplos de 3 e 5.</h1>
<div class="main">
    @foreach(var numero in Model)
    {
        @if(numero == "FIZZ")
        {
            multiploTres++;
            <div class="d-inline p-2 bg-primary text-white multiplo indigo">@numero</div>
        } 
        else if(numero == "BUZZ")
        {
            multiploCinco++;
            <div class="d-inline p-2 bg-primary text-white multiplo blue">@numero</div>
        } 
        else if(numero == "FIZZBUZZ")
        {
            multiloTresCinco++;
            <div class="d-inline p-2 bg-primary text-white multiplo teal">@numero</div>
        } 
        else 
        {
            outroMultiplo++;
            <div class="d-inline p-2 bg-primary text-white multiplo green">@numero</div>
        }
    }
    <ul>
        <li><span class="green">@outroMultiplo</span> número* (Multiplo de outros números)</li>
        <li><span class="indigo">@multiploTres</span>FIZZ (Multiplo de 3)</li>
        <li><span class="blue">@multiploCinco</span>BUZZ (Multiplo de 5)</li>
        <li><span class="teal">@multiloTresCinco</span>FIZZBUZZ (Multiplo de 3 e 5)</li>
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MULTIPLOS MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Actions" asp-action="Index" class="navbar-brand">MULTIPLOS MVC</a>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Bruno Afonso.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>